title: <p align="center"> Amit Kumar </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/amitdeshu">GitHub</a>
  
  <br>   
  I'm learning AI/ML
  <br>
  </p>



theme: jekyll-theme-minimal
